<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>CICMessenger.Translate</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CICMessenger.Client\CICMessenger.Client.csproj" />
    <ProjectReference Include="..\CICMessenger.Utilities\CICMessenger.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\AssemblyInfo.Copyright.cs" Link="Properties\AssemblyInfo.Copyright.cs" />
  </ItemGroup>
</Project>
